application:
  name: '@project.artifactId@'

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: 'update'
  datasource:
#    initialization-mode: ALWAYS
    url: jdbc:mysql://localhost:3306/list-app-db?serverTimezone=UTC
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: h2

list-app:
  jwtSecret: secretKey
  jwtExpirationMs: 86400000

management:
  endpoints:
    web:
      exposure:
        include: "*"